modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Crimix/jetboots/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]]
modId="jetboots"
authors="black_dog20"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jet-boots"
version="${file.jarVersion}"
displayName="Jet Boots"
updateJSONURL="https://raw.githubusercontent.com/Crimix/jetboots/1.17/update.json"
logoFile="jetboots-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
description='''Flying has never been this fun'''

[[dependencies.jetboots]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.17,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jetboots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jetboots]]
    modId="blackdogsmoddinglibrary"
    mandatory=true
    versionRange="[1.1.4,)"
    ordering="BEFORE"
    side="BOTH"