modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Crimix/jetboots/issues"


[[mods]]
modId="jetboots"
authors="black_dog20"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jet-boots"
version="${file.jarVersion}"
displayName="Jet Boots"
updateJSONURL="https://raw.githubusercontent.com/Crimix/jetboots/1.16/update.json"
logoFile="jetboots-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
description='''Flying has never been this fun'''

[[dependencies.jetboots]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jetboots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.jetboots]]
    modId="blackdogsmoddinglibrary"
    mandatory=true
    versionRange="[1.1.2,)"
    ordering="BEFORE"
    side="BOTH"